# Generated by Django 4.0.6 on 2022-07-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyModels', '0002_targetexamtype_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='educational_details',
            new_name='education',
        ),
        migrations.AddField(
            model_name='profile',
            name='mname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
