# Generated by Django 4.0.6 on 2022-07-16 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlyModels', '0003_rename_educational_details_profile_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_ans', models.TextField(blank=True, null=True, verbose_name='Subjective Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(0, 'Student'), (1, 'Examiner'), (2, 'Both')], verbose_name='Selected Role'),
        ),
        migrations.CreateModel(
            name='MCQues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(verbose_name='Question')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlyModels.answer', verbose_name='Answer')),
                ('options', models.ManyToManyField(to='onlyModels.option', verbose_name='Options')),
            ],
            options={
                'verbose_name': 'MCQ',
                'verbose_name_plural': 'MCQs',
            },
        ),
        migrations.CreateModel(
            name='MAQues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(verbose_name='Question')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlyModels.answer', verbose_name='Answer')),
                ('options', models.ManyToManyField(to='onlyModels.option', verbose_name='Options')),
            ],
            options={
                'verbose_name': 'Multiple Answer Question',
                'verbose_name_plural': 'Multiple Answer Questions',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='obj_ans',
            field=models.ManyToManyField(to='onlyModels.option', verbose_name='ObjectiveAnswer'),
        ),
    ]
