# Generated by Django 4.0.6 on 2022-07-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyModels', '0005_alter_answer_obj_ans_alter_profile_education'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MAQues',
            new_name='Question',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'MCQ', 'verbose_name_plural': 'MCQs'},
        ),
        migrations.AddField(
            model_name='profile',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Is Profile Completed?'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='obj_ans',
            field=models.ManyToManyField(blank=True, null=True, to='onlyModels.option', verbose_name='Objective Answer'),
        ),
        migrations.DeleteModel(
            name='MCQues',
        ),
    ]
