# Generated by Django 4.0.6 on 2022-07-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyModels', '0007_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
