# Generated by Django 4.0.6 on 2022-07-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyModels', '0011_alter_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(0, 'Student'), (1, 'Examiner'), (2, 'Both')], default=0, verbose_name='Selected Role'),
        ),
    ]
