# Generated by Django 4.0.6 on 2022-07-26 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlyModels', '0014_subjects_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='exam_tags',
            field=models.ManyToManyField(to='onlyModels.targetexamtype', verbose_name='Exam Tags'),
        ),
        migrations.AddField(
            model_name='question',
            name='subjext_tags',
            field=models.ManyToManyField(to='onlyModels.subjects', verbose_name='Subject Tags'),
        ),
        migrations.AlterField(
            model_name='option',
            name='opt',
            field=models.TextField(verbose_name='Options'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fname',
            field=models.CharField(max_length=150, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lname',
            field=models.CharField(max_length=150, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mname',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(max_length=14, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='onlyModels.answer', verbose_name='Answer'),
        ),
    ]
