# Generated by Django 4.0.6 on 2022-07-26 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlyModels', '0015_question_exam_tags_question_subjext_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_level', models.IntegerField(choices=[(0, 'Beginner'), (1, 'Intermediate'), (2, 'Advance')], default=0, verbose_name='Exam Level')),
                ('allowed_attempts', models.IntegerField(default=1, verbose_name='Allowed no. of attemps')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='subjext_tags',
            new_name='subject_tags',
        ),
        migrations.CreateModel(
            name='ExamAttempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Attempted by')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlyModels.exam', verbose_name='Exam')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(to='onlyModels.question', verbose_name='Questions'),
        ),
    ]
