# Generated by Django 4.0.6 on 2022-07-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyModels', '0017_alter_profile_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='exam_tags',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_tags',
            field=models.ManyToManyField(to='onlyModels.targetexamtype', verbose_name='Exam Tags'),
        ),
        migrations.AddField(
            model_name='exam',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Created at'),
        ),
    ]
