# Generated by Django 4.0.6 on 2022-07-31 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onlyModels', '0018_remove_question_exam_tags_exam_exam_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Duration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='name',
            field=models.CharField(default='Exam', max_length=300, verbose_name='Exam Name'),
            preserve_default=False,
        ),
    ]
