# Generated by Django 4.0.6 on 2022-07-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyModels', '0020_alter_exam_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.BigIntegerField(verbose_name='Duration(minutes)'),
        ),
    ]
